'use strict';
// Generated by scripts/build-credit-referee.cjs. Browser state is never trusted.
const crypto=require('node:crypto');
function createReferee(session,{now=Date.now(),deckFactory=serverDeck}={}){
const state={room:session.room,roomCode:session.code,localGame:true,playerId:'player1',localHands:session.hands||{},localOriginalHands:session.originals||{},localTruth:session.truth||{},hand:[]};
const VALID_TARGET_POINTS=[10,20,30,40,50,60];
const gameTime=()=>now;
const noop=()=>{};
const renderGame=noop,queueLearningPoints=noop,queueLearningAction=noop,queueLearningTrucoCall=noop,queueLearningRoundResult=noop,animatePlayedHandCard=noop,renderTurnTimer=noop,renderRoundPauseTimer=noop;
const liveActionsBlocked=()=>false,finishLearningHand=()=>false;
const learningDeck=()=>deckFactory();
const verifiedHandTruth=()=>state.localTruth;
const toast=text=>{throw new Error(text);};
const shakeTurnBadge=()=>{throw new Error('No es tu turno.');};
const pauseMessage=()=>state.room.resolvingTrick||state.room.pendingNextHand||state.room.status==='revealing';
const scheduleLocalTransition=noop,scheduleLocalNextHand=noop;
const $=()=>({dataset:{value:'0'}});

function pieceOrder(card, muestra) {
  if (!muestra) return 0;
  let rank = Number(card.rank);
  if (card.suit !== muestra.suit) return 0;
  if ([2,4,5,10,11].includes(Number(muestra.rank))) {
    if (rank === Number(muestra.rank)) rank = 12;
    else if (rank === 12) rank = Number(muestra.rank);
  }
  return ({2:5,4:4,5:3,11:2,10:1})[rank] || 0;
}
function cardStrength(card, muestra) {
  const piece = pieceOrder(card, muestra);
  if (piece) return 100 + piece;
  const matas = {'♠-1':90,'♣-1':89,'♠-7':88,'♦-7':87};
  const mata = matas[`${card.suit}-${card.rank}`];
  if (mata) return mata;
  const common = {3:80,2:70,1:60,12:50,11:40,10:30,7:20,6:10,5:5,4:0};
  return common[card.rank] || 0;
}
function envidoValue(card, muestra) {
  const piece = pieceOrder(card, muestra);
  if (piece) return ({5:30,4:29,3:28,2:27,1:27})[piece];
  return [10,11,12].includes(Number(card.rank)) ? 0 : Number(card.rank);
}
function hasFlor(hand, muestra) {
  // Flor: tres del mismo palo, dos o más piezas, o una pieza y dos del mismo palo.
  const pieces = hand.filter((card)=>pieceOrder(card,muestra)>0);
  const suits = hand.reduce((all,card)=>{all[card.suit]=(all[card.suit]||0)+1;return all;},{});
  const nonPieces=hand.filter((card)=>!pieceOrder(card,muestra));
  const twoSameSuit=nonPieces.length===2&&nonPieces[0].suit===nonPieces[1].suit;
  const threeSameSuit=Object.values(suits).some((n)=>n===3);
  return threeSameSuit || pieces.length>=2 || (pieces.length===1&&twoSameSuit);
}
function handEnvido(hand, muestra) {
  const values=hand.map((card)=>envidoValue(card,muestra));let best=Math.max(...values);
  const pieces=hand.map((card,index)=>pieceOrder(card,muestra)?index:-1).filter((index)=>index>=0);
  if(pieces.length===1){const p=pieces[0],others=values.filter((_,index)=>index!==p);best=Math.max(best,values[p]+Math.max(...others));}
  for(let a=0;a<hand.length;a++)for(let b=a+1;b<hand.length;b++)if(!pieceOrder(hand[a],muestra)&&!pieceOrder(hand[b],muestra)&&hand[a].suit===hand[b].suit)best=Math.max(best,20+values[a]+values[b]);
  return best;
}
function florValue(hand,muestra) {
  const pieces=hand.filter(card=>pieceOrder(card,muestra)>0).map(card=>envidoValue(card,muestra)).sort((a,b)=>b-a);
  const common=hand.filter(card=>!pieceOrder(card,muestra)).reduce((sum,card)=>sum+envidoValue(card,muestra),0);
  return pieces.length?pieces[0]+pieces.slice(1).reduce((sum,value)=>sum+value%10,0)+common:20+common;
}
function normalizeTargetPoints(value) {
  const parsed=Number(value);
  return VALID_TARGET_POINTS.includes(parsed)?parsed:30;
}
function targetPoints(room) { return normalizeTargetPoints(room?.targetPoints); }
function capScores(room,scores){
  const maximum=targetPoints(room);
  return Object.fromEntries(Object.entries(scores||{}).map(([player,value])=>[player,Math.min(maximum,Math.max(0,Number(value)||0))]));
}
function faltanParaGanar(room) { return Math.max(1,targetPoints(room)-Math.max(Number(room.scores?.player1)||0,Number(room.scores?.player2)||0)); }
function faltaEnvidoPoints(room){
  const target=targetPoints(room),leader=Math.max(Number(room.scores?.player1)||0,Number(room.scores?.player2)||0);
  return leader<target/2?target:faltanParaGanar(room);
}
function envidoBetPoints(room,kind,base=0){
  if(kind==='falta')return faltaEnvidoPoints(room);
  const points=(Number(base)||0)+(kind==='real'?3:2);
  return points>faltanParaGanar(room)?2:points;
}
function florBetPoints(room,kind){
  return kind==='falta'?targetPoints(room):5;
}
function declinedFlorPoints(bet){
  return bet.called==='conflor'?3:(Number(bet.accepted)||3);
}
function florAnswers(bet,hasFlower){
  if(bet.single)return hasFlower?[['yes','FLOR'],['raise-conflor','CON FLOR ENVIDO'],['raise-faltaflor','CONTRA FLOR AL RESTO']]:[['no','TIENE']];
  if(bet.called==='falta')return [['yes','QUIERO'],['no','NO QUIERO']];
  if(bet.called==='conflor')return [['yes','QUIERO'],['no','NO QUIERO'],['raise-faltaflor','CONTRA FLOR AL RESTO']];
  return [['yes','LA MÍA ES FLOR'],['raise-conflor','CON FLOR ENVIDO'],['raise-faltaflor','CONTRA FLOR AL RESTO']];
}
function otherPlayer(player){return player==='player1'?'player2':'player1';}
function settleHand(tricks,room){
  if(tricks.length<2)return null;
  const first=tricks[0].winner,second=tricks[1].winner;
  if(first&&(!second||first===second))return first;
  if(!first&&second)return second;
  if(tricks.length<3)return null;
  return tricks[2].winner||first||room.mano||'player1';
}
function topFeed(room,text) { return [{text,time:Date.now()},...(room.feed||[]).slice(0,7)]; }
function spokenCall(text=''){
  if(/\bdice QUIERO\b/i.test(text))return 'Quiero';
  if(/\bresponde:\s*tiene\b/i.test(text))return 'Tiene';
  if(/se fue al mazo/i.test(text))return 'Me voy al mazo';
  const points=text.match(/\bcanta (\d+) (tantos|son mejores|son iguales)\b/i);
  if(points)return `${points[1]} ${points[2]}`;
  if(/: son buenas\./i.test(text))return 'Son buenas';
  if(!/\b(canta|dice|responde|quiere)\b/i.test(text))return null;
  if(/no quiere/i.test(text))return 'No quiero';
  if(/quiere/i.test(text))return 'Quiero';
  return ['contra flor al resto','con flor envido','falta envido','real envido','envido','vale cuatro','retruco','truco','flor'].find(call=>text.toLowerCase().includes(call))||null;
}
function callNoticeText(text=''){
  return text.replace(/\bcanta (?=(?:envido|real envido|falta envido|truco|retruco|vale cuatro)\b)/gi,'dice ').replace(/(\bcanta flor\.)[\s\S]*$/i,'$1');
}
function ownCallVerb(main,bet){
  const call=main.toLocaleLowerCase('es-UY');
  if(call==='truco')return 'Gritaste';
  if(call==='flor')return 'Cantaste';
  if(call==='envido'&&!(bet?.calls?.length>1)&&!(bet?.accepted>0))return 'Tocaste';
  return 'Dijiste';
}
function makeCallNotice(text,bet=state.room?.pendingBet){
  text=callNoticeText(text);
  const spoken=spokenCall(text);
  if(!spoken||!['player1','player2'].includes(state.playerId))return null;
  return {...(spoken==='Me voy al mazo'?{kind:'fold'}:{}),id:crypto.randomUUID(),from:state.playerId,to:state.playerId==='player1'?'player2':'player1',text:spoken==='Tiene'||spoken==='Me voy al mazo'?text.split('.')[0]+'.':/\bcanta \d+ (tantos|son mejores|son iguales)\b/i.test(text)?spoken:text,spoken,selfVerb:ownCallVerb(spoken,bet),time:Date.now(),handNumber:state.room?.handNumber||1};
}
function canRaiseEnvido(bet){
  return bet?.type==='envido'&&!bet.revealMode&&bet.called!=='falta'&&!(bet.calls||[]).includes('falta');
}
function roomHasFlor(room,hand){return room?.practiceRules?.flor!==false&&hasFlor(hand,room?.muestra);}
function canCallFirstRoundEnvido(room,player,hand){
  if(!room||room.practiceRules?.envido===false||room.status!=='started'||!['player1','player2'].includes(player)||room.resolvingTrick||room.pendingNextHand||Number(room.trickNo||1)!==1)return false;
  if(room.envidoClosed||Object.keys(room.flors||{}).length>0||room.pendingBet?.type==='flor'||room.florSettled||Number(room.playedCount||0)>=2||(room.trickCards||[]).some(item=>item.playerId===player))return false;
  return !!hand?.length&&!room.flors?.[player]&&!room.flors?.[otherPlayer(player)]&&!roomHasFlor(room,hand);
}
function declinedTrucoChanges(room,player){
  const bet=room.pendingBet,points=Math.max(1,Number(bet.stake||2)-1);
  const message=(room.players?.[player]?.name||'El jugador')+' no quiere. '+(room.players?.[bet.caller]?.name||'El rival')+' suma '+points+'.';
  return {turn:null,turnClock:null,pendingBet:null,envidoClosed:true,
    pendingNextHand:{id:'declined:'+crypto.randomUUID(),winner:bet.caller,foldPoints:points,message,endsAt:gameTime()+3000},
    callNotice:makeCallNotice((room.players?.[player]?.name||'El jugador')+' no quiere.'),
    feed:topFeed(room,message)};
}
function revealEnvido(good=false,declaredNumber=null) {
  if(liveActionsBlocked())return;
  if(state.learning?.paused)return;
  if(state.room?.turnClock?.key===turnClockKey()&&turnClockRemaining(state.room.turnClock).expired){renderTurnTimer();return;}
  const room=state.room,bet=room?.pendingBet,player=state.playerId;
  if(bet?.type!=='envido'||!bet.revealMode||bet.revealTurn!==player)return;
  const first=room.mano,second=otherPlayer(first),number=Number(declaredNumber??($('envido-picker').dataset.value||0));
  if(good&&player!==second)return;
  if(!good&&(!Number.isInteger(number)||number<0||number>50||(player===second&&number<bet.reveals?.[first]))){toast('Igualá o superá los tantos.');return;}
  const reveals={...(bet.reveals||{})};if(!good)reveals[player]=number;
  let changes;
  if(player===first){changes={pendingBet:{...bet,reveals,revealTurn:second},feed:topFeed(room,`${room.players[player].name} canta ${number} tantos.`)};}
  else{
    const winner=good||number===Number(bet.reveals?.[first])?first:second;
    changes={pendingBet:bet.suspendedBet||null,envidoClosed:true,envidoAudit:{reveals,declarationOrder:[first,second].filter(p=>reveals[p]!=null),winner,stake:bet.stake,called:bet.called||'envido',calls:bet.calls||[bet.called||'envido'],handNumber:room.handNumber},feed:topFeed(room,good?`${room.players[player].name}: son buenas.`:`${room.players[player].name} canta ${number} ${number===Number(bet.reveals?.[first])?'son iguales':'son mejores'}.`)};
  }
  const finishFalta=player===second&&bet.called==='falta';
  if(finishFalta){changes={...changes,pendingBet:null,turn:null,turnClock:null,pendingNextHand:{id:'falta:'+crypto.randomUUID(),winner:changes.envidoAudit.winner,foldPoints:0,endsAt:gameTime(),message:'Falta envido: se verifican los tantos y se asignan '+bet.stake+' puntos.'}};}
  if(state.localGame){queueLearningAction(good?'good':'declare',bet);const notice=makeCallNotice(changes.feed?.[0]?.text);if(notice)changes.callNotice=notice;Object.assign(room,changes);if(finishFalta){room.pendingNextHand=null;localFinishHand(changes.envidoAudit.winner,0,'falta');return;}renderGame();}else throw new Error('Server state required.');
}
function envidoAuditResult(room,truth){
  const audit=room.envidoAudit;
  if(!audit)return {liars:[],winner:null};
  const order=audit.declarationOrder||[room.mano||'player1',otherPlayer(room.mano||'player1')];
  const liars=order.filter(player=>audit.reveals?.[player]!=null&&Number(audit.reveals[player])!==Number(truth[player]));
  const declaredWinner=audit.reveals?.player1!=null&&audit.reveals.player1===audit.reveals.player2?room.mano:audit.winner;
  return {liars,winner:liars.length?otherPlayer(liars[0]):declaredWinner};
}
function settleAuditedHand(room,scores,truth,winner,points){
  const result=auditEnvidoScores(room,scores,truth),audit=envidoAuditResult(room,truth);
  const handWinner=audit.liars.length?audit.winner:winner;
  const handPoints=audit.liars.length?(Number(points)||Number(room.trucoLevel)||1):Number(points)||0;
  if(handWinner&&handPoints)result[handWinner]=(Number(result[handWinner])||0)+handPoints;
  return result;
}
function auditEnvidoScores(room,scores,truth){
  if(!room.envidoAudit)return scores;
  const {winner}=envidoAuditResult(room,truth),result={...scores};
  if(winner)result[winner]=(result[winner]||0)+Number(room.envidoAudit.stake);
  return result;
}
function settleSingleFlor(room,scores) {
  const flowers=Object.keys(room.flors||{});
  if(flowers.length!==1||room.florSettled)return scores;
  const player=flowers[0];return {...scores,[player]:(Number(scores[player])||0)+3};
}
function envidoEvidenceCards(hand,muestra){
  if(!hand?.length)return [];
  const options=hand.map(card=>({cards:[card],value:envidoValue(card,muestra)}));
  for(let a=0;a<hand.length;a++)for(let b=a+1;b<hand.length;b++){
    const x=hand[a],y=hand[b],px=pieceOrder(x,muestra),py=pieceOrder(y,muestra);
    if(px||py)options.push({cards:[x,y],value:envidoValue(x,muestra)+envidoValue(y,muestra)});
    else if(x.suit===y.suit)options.push({cards:[x,y],value:20+envidoValue(x,muestra)+envidoValue(y,muestra)});
  }
  return options.find(option=>option.value===handEnvido(hand,muestra))?.cards||hand;
}
function buildEndEvidence(room,originals){
  const groups=[];
  for(const player of Object.keys(room.flors||{})){
    const cards=originals[player]||[];
    if(cards.length===3)groups.push({player,label:Object.keys(room.flors||{}).length>1?'Flor · '+florValue(cards,room.muestra)+' tantos':'Flor',cards});
  }
  const audit=room.envidoAudit;
  if(audit){
    const truth={player1:handEnvido(originals.player1||[],room.muestra),player2:handEnvido(originals.player2||[],room.muestra)};
    const {liars,winner}=envidoAuditResult(room,truth);
    for(const player of Object.keys(audit.reveals||{})){
      if(originals[player]?.length!==3)continue;
      const declared=audit.reveals?.[player];
      const label=liars.includes(player)?`Envido · dijo ${declared}, tenía ${truth[player]}`:`Envido · ${truth[player]} tantos`;
      groups.push({player,label,cards:envidoEvidenceCards(originals[player],room.muestra),envidoAward:{player:winner,points:Math.min(Number(audit.stake),Math.max(0,targetPoints(room)-Number(room.scores?.[winner]||0)))}});
    }
  }
  return groups;
}
function betCallNames(bet){
  const names=bet.type==='flor'?{flor:'Flor',conflor:'Con flor envido',falta:'Contra flor al resto'}:{envido:'Envido',real:'Real envido',falta:'Falta envido'};
  return (bet.calls?.length?bet.calls:[bet.called||(bet.type==='flor'?'flor':'envido')]).map(kind=>names[kind]||kind);
}
function declinedBetExplanation(room,bet){
  const points=bet.type==='flor'?declinedFlorPoints(bet):(Number(bet.accepted)||1);
  const rival=room.players?.[bet.responder]?.name||'el rival',calls=betCallNames(bet);
  const reason=bet.type==='flor'?(bet.called==='conflor'?'Se suman solo los 3 puntos de la flor.':'Se suman '+points+' puntos de la flor ya en juego.'):Number(bet.accepted)>0?'Se suman los '+points+' puntos del canto anterior; el último canto no fue aceptado.':'Un envido no querido suma 1 punto.';
  return calls.join(' + ')+' no querido por '+rival+'. '+reason;
}
function acceptedEnvidoExplanation(audit){
  const bet={...audit,type:'envido'},calls=betCallNames(bet),kinds=audit.calls||[audit.called||'envido'];
  const values=kinds.map(kind=>kind==='envido'?2:kind==='real'?3:null);
  const sum=values.every(value=>value!==null)?values.reduce((total,value)=>total+value,0):null;
  const points=Number(audit.stake)||0;
  const calculation=sum===points?values.join(' + ')+' = '+points+' puntos.':kinds.includes('falta')?'Se juega por '+points+' puntos de falta envido.':'Se juega por 2 puntos porque el canto supera lo que falta para ganar.';
  return calls.join(' + ')+' querido. '+calculation;
}
function scoringEntries(room,scores,reason,truth=null){
  const entries=[...(room.handScoreEntries||[])];
  const remaining={player1:Number(scores.player1||0)-Number(room.scores?.player1||0),player2:Number(scores.player2||0)-Number(room.scores?.player2||0)};
  const add=(player,points,detail)=>{if(points>0){entries.push({player,points,detail});remaining[player]-=points;}};
  if(room.envidoAudit&&truth){
    const audit=room.envidoAudit,award=auditEnvidoScores(room,{player1:0,player2:0},truth);
    const names=p=>room.players?.[p]?.name||'Jugador';
    const details=['player1','player2'].map(p=>audit.reveals?.[p]!=null?`${names(p)} declaró ${audit.reveals[p]} y tenía ${truth[p]}.`:`${names(p)} tenía ${truth[p]} tantos.`);
    const liars=Object.keys(audit.reveals||{}).filter(p=>Number(audit.reveals[p])!==Number(truth[p]));
    const result=liars.length===2?`${names(envidoAuditResult(room,truth).liars[0])} declaró mal primero; el rival gana el envido y la mano.`:liars.length===1?`${names(liars[0])} declaró tantos incorrectos; el rival gana el envido y la mano.`:audit.reveals?.player1===audit.reveals?.player2&&audit.reveals?.player1!=null?'Empate: gana quien es mano.':'Gana el envido.';
    const detail=acceptedEnvidoExplanation(audit)+' '+details.join(' ')+' '+result;
    for(const p of ['player1','player2'])if(award[p]>0&&remaining[p]>=award[p])add(p,award[p],detail);
    if(!award.player1&&!award.player2)entries.push({player:room.mano||'player1',points:0,detail});
  }
  if(['envido','flor'].includes(room.pendingBet?.type)&&/no (?:quiere|querido)|responde: tiene/i.test(reason||'')){
    for(const player of ['player1','player2'])if(remaining[player]>0)add(player,remaining[player],declinedBetExplanation(room,room.pendingBet));
    return entries;
  }
  if(room.pendingBet?.type==='flor'&&room.pendingBet.called==='conflor'){
    for(const player of ['player1','player2'])if(remaining[player]>=5){
      add(player,3,'Con flor envido · 3 puntos de la flor.');
      add(player,2,'Con flor envido · 2 puntos del envido.');
    }
  }
  const flowers=Object.keys(room.flors||{});
  if(flowers.length===1&&!room.florSettled&&remaining[flowers[0]]>=3)add(flowers[0],3,`Flor sin rival (${room.flors[flowers[0]]} tantos): suma 3 puntos.`);
  for(const p of ['player1','player2'])if(remaining[p]>0)add(p,remaining[p],reason?.includes('gana la mano')?`Mano ganada${Number(room.trucoLevel)>1?' · '+({2:'Truco',3:'Retruco',4:'Vale cuatro'}[room.trucoLevel]||'Truco')+' aceptado':''}.`:(reason||'Puntos de la mano.'));
  return entries;
}
function buildHandSummary(room,scores,reason,truth=verifiedHandTruth(room)){
  const entries=scoringEntries(room,scores,reason,truth);
  const totals={player1:0,player2:0};
  entries.forEach(entry=>{totals[entry.player]+=Number(entry.points)||0;});
  return {handNumber:room.handNumber||1,totals,entries,names:{player1:room.players?.player1?.name||'Jugador 1',player2:room.players?.player2?.name||'Jugador 2'},time:Date.now()};
}
function handScoreHistory(room, summary=null){
  const history={...(room?.handScoreHistory||{})};
  for(const hand of [room?.lastHandScore,summary]){
    if(hand)history[hand.handNumber]=hand;
  }
  return history;
}
function localHand(player){return state.localHands?.[player]||[];}
function localFeed(text){state.room.feed=[{text,time:Date.now()},...(state.room.feed||[])].slice(0,8);const notice=makeCallNotice(text);if(notice)state.room.callNotice=notice;}
function localScore(player,points,description){
  const amount=Math.max(0,Number(points)||0);if(!amount)return;
  const before={...state.room,scores:{...state.room.scores}};
  state.room.scores[player]=Math.min(targetPoints(state.room),(state.room.scores[player]||0)+amount);
  state.room.handScoreEntries=scoringEntries(before,state.room.scores,description);
  queueLearningPoints(before,state.room.scores,state.room.handScoreEntries);
  localFeed(`${state.room.players[player].name} ${description} (+${amount}).`);
  if(state.room.scores[player]>=targetPoints(state.room)){state.room.status='complete';state.room.lastHandScore=buildHandSummary(before,state.room.scores,description,null);state.room.handScoreHistory=handScoreHistory(state.room,state.room.lastHandScore);}
}
function localResolveFlor(bet){
  const values=state.room.flors||{};if(values.player1==null||values.player2==null)return;
  const winner=values.player1===values.player2?(state.room.mano||'player1'):(values.player1>values.player2?'player1':'player2');
  localScore(winner,bet.stake||3,`gana las flores (${values.player1} a ${values.player2})`);
  state.room.pendingBet=bet.suspendedBet||null;state.room.envidoClosed=true;state.room.florSettled=true;
}
function localCallAction(kind){
  if(state.learning?.paused)return;
  const room=state.room,caller=state.playerId;if(!room||room.status!=='started'||room.resolvingTrick||room.pendingNextHand||!localHand(caller).length)return;
  const other=otherPlayer(caller),pending=room.pendingBet;
  const overTruco=pending?.type==='truco'&&pending.responder===caller;
  
  if(pending&&!overTruco){toast('Respondé el canto.');return;}
  if(['envido','real','falta'].includes(kind)){
    if(!canCallFirstRoundEnvido(room,caller,localHand(caller))){toast('El envido está cerrado o hay flor.');return;}
    const base=pending?.type==='envido'?(pending.stake||0):0;
    room.pendingBet={type:'envido',caller,responder:other,stake:envidoBetPoints(room,kind,base),accepted:base,called:kind,calls:[kind],reveals:{},suspendedBet:overTruco?pending:null};
    queueLearningAction(kind);localFeed(`${room.players[caller].name} canta ${kind==='real'?'real envido':kind==='falta'?'falta envido':'envido'}.`);renderGame();return;
  }
  if(['truco','retruco','vale4'].includes(kind)){
    const wanted={truco:2,retruco:3,vale4:4}[kind],level=Number(room.trucoLevel)||1;
    if(pending||wanted!==level+1||level>=4||(level>1&&room.lastTrucoCaller===caller)){toast('Ese canto no está disponible.');return;}
    room.pendingBet={type:'truco',caller,responder:other,stake:wanted};room.lastTrucoCaller=caller;
    queueLearningTrucoCall(wanted,caller);
    localFeed(`${room.players[caller].name} canta ${kind==='vale4'?'vale cuatro':kind}.`);renderGame();
  }
}
function localAnswerAction(answer){
  if(state.learning?.paused)return;
  if(state.room?.turnClock?.key===turnClockKey()&&turnClockRemaining(state.room.turnClock).expired){renderTurnTimer();return;}
  const room=state.room,bet=room?.pendingBet,player=state.playerId;if(!bet)return;
  if(bet.type==='envido'&&bet.revealMode&&answer==='yes'){
    revealEnvido();return;
  }
  if(bet.responder!==player)return;
  if(bet.type==='envido'&&roomHasFlor(room,localHand(player))){toast('Tenés flor. Cantá flor.');return;}
  if(bet.type==='flor'&&!florAnswers(bet,roomHasFlor(room,localHand(player))).some(([action])=>action===answer))return;
  if(bet.type==='flor'&&bet.single&&answer==='yes'){localAction('flor');return;}
  if(answer==='raise'&&bet.type==='truco'){
    const value=bet.stake===2?3:4;room.pendingBet={...bet,caller:player,responder:bet.caller,stake:value};room.lastTrucoCaller=player;queueLearningTrucoCall(value,player);localFeed(`${room.players[player].name} canta ${value===3?'retruco':'vale cuatro'}.`);renderGame();return;
  }
  if(answer.startsWith('raise-')&&bet.type==='envido'){
    if(!canRaiseEnvido(bet))return;
    const kind=answer.slice(6),value=envidoBetPoints(room,kind,bet.stake);
    room.pendingBet={...bet,caller:player,responder:bet.caller,accepted:bet.stake,stake:value,called:kind,calls:[...(bet.calls||[bet.called||'envido']),kind],reveals:{}};queueLearningAction(answer);localFeed(`${room.players[player].name} canta ${kind==='falta'?'falta envido':kind==='real'?'real envido':'envido'}.`);renderGame();return;
  }
  if(bet.type==='flor'&&(answer==='raise-conflor'||answer==='raise-faltaflor')){
    const kind=answer==='raise-faltaflor'?'falta':'conflor',value=florBetPoints(room,kind);room.flors={...room.flors,[player]:florValue(localHand(player),room.muestra)};room.pendingBet={...bet,single:false,caller:player,responder:bet.caller,accepted:bet.stake,stake:value,called:kind,calls:[...(bet.calls||[bet.called||'flor']),kind]};queueLearningAction(answer);localFeed(`${room.players[player].name} responde ${kind==='conflor'?'con flor envido':'contra flor al resto'}.`);renderGame();return;
  }
  if(answer==='yes'||answer==='no')queueLearningAction(answer,bet);
  if(answer==='no'){
    localFeed(`${room.players[player].name} ${bet.type==='flor'&&bet.single?'responde: tiene':'no quiere'}.`);
    const points=bet.type==='truco'?Math.max(1,(bet.stake||2)-1):bet.type==='flor'?declinedFlorPoints(bet):(bet.accepted||1);
    if(bet.type==='truco'){Object.assign(room,declinedTrucoChanges(room,player));renderGame();scheduleLocalNextHand(room);return;}
    if(bet.type==='flor')room.florSettled=true;
    localScore(bet.caller,points,`${bet.type==='envido'?'Envido':bet.type==='flor'?'Flor':'Truco'} no querido por ${room.players[player].name}`);room.pendingBet=bet.suspendedBet||null;room.envidoClosed=true;renderGame();return;
  }
  if(bet.type==='envido'){
    room.pendingBet={...bet,reveals:{},revealMode:true,revealTurn:room.mano};localFeed(`${room.players[player].name} quiere. Declara primero ${room.players[room.mano].name}.`);renderGame();return;
  }
  if(bet.type==='flor'){localFeed(`${room.players[player].name} quiere.`);localResolveFlor(bet);renderGame();return;}
  room.trucoLevel=bet.stake;room.pendingBet=null;localFeed(`${room.players[player].name} dice QUIERO`);renderGame();
}
function localAction(action){
  if(state.learning?.paused)return;
  if(action==='reveal')localAnswerAction('yes');
  else if(action==='flor'){
    const room=state.room,player=state.playerId;if(room.playedCount>0||room.flors?.[player]!=null||!roomHasFlor(room,localHand(player))){toast('No tenés flor.');return;}
    const overEnvido=room.pendingBet?.type==='envido'&&room.pendingBet.responder===player;
    const other=otherPlayer(player);room.flors={...(room.flors||{}),[player]:florValue(localHand(player),room.muestra)};room.envidoClosed=true;
    const suspendedBet=room.pendingBet?.type==='truco'?room.pendingBet:(room.pendingBet?.suspendedBet||null);
    room.pendingBet={type:'flor',called:'flor',single:!room.flors[other],caller:player,responder:other,stake:3,accepted:0,suspendedBet};
    queueLearningAction('flor');localFeed(`${room.players[player].name} canta flor.`);
    if(overEnvido&&!room.flors[other]){
      room.florSettled=true;room.pendingBet=suspendedBet;
      localScore(player,3,'gana la flor; se cancela el envido');
    }
    renderGame();
  } else if(['yes','no','raise'].includes(action)||action.startsWith('raise-'))localAnswerAction(action);
  else localCallAction(action);
}
function localPlay(card,launchOrigin=null) {
  if(state.learning?.paused)return;
  if(state.room?.turnClock?.key===turnClockKey()&&turnClockRemaining(state.room.turnClock).expired){renderTurnTimer();return;}
  const player=state.playerId;
  const pause=pauseMessage();if(pause){renderRoundPauseTimer();return;}
  if(state.room.status!=='started')return;
  if(state.room.pendingBet){shakeTurnBadge();return;}
  if(state.room.turn!==player){shakeTurnBadge();return;}
  animatePlayedHandCard(card,launchOrigin);
  state.localHands[player]=(state.localHands[player]||[]).filter((item)=>item.id!==card.id);state.hand=[...state.localHands[player]];state.room.playedCount=(state.room.playedCount||0)+1;
  state.room.trickCards=[...(state.room.trickCards||[]),{playerId:player,name:state.room.players[player].name,card}];state.room.deckCount--;
  if(state.room.trickCards.length===2){
    const first=state.room.trickCards[0],second=state.room.trickCards[1],winner=cardStrength(first.card,state.room.muestra)===cardStrength(second.card,state.room.muestra)?null:(cardStrength(first.card,state.room.muestra)>cardStrength(second.card,state.room.muestra)?first.playerId:second.playerId);
    state.room.tricks=[...(state.room.tricks||[]),{winner,played:[...state.room.trickCards]}];
    queueLearningRoundResult(winner,state.room.trickCards);
    const handWinner=settleHand(state.room.tricks,state.room);
    if(winner)state.room.feed.unshift({text:`${state.room.players[winner].name} se lleva la ronda.`,time:Date.now()});
    state.room.resolvingTrick=true;state.room.resolutionId=crypto.randomUUID();state.room.resolutionEndsAt=gameTime()+3000;state.room.resolvedTrickWinner=winner;state.room.handComplete=!!handWinner;
    const resolvingRoom=state.room;
    scheduleLocalTransition(resolvingRoom,()=>{if(!state.localGame||state.room!==resolvingRoom)return;state.room.resolvingTrick=false;state.room.resolutionEndsAt=null;state.room.handComplete=false;state.room.trickCards=[];if(handWinner){localFinishHand(handWinner,state.room.trucoLevel||1);return;}else{state.room.turn=winner||state.room.mano;state.room.trickNo++;}state.hand=[...(state.localHands[state.playerId]||[])];renderGame();},3000);
  }else state.room.turn=player==='player1'?'player2':'player1';
  renderGame();
}
function localFinishHand(winner,points,ending='rounds'){
  const room=state.room,before={...room,scores:{...room.scores}},groups=buildEndEvidence(room,state.localOriginalHands||{}),auditResult=envidoAuditResult(room,state.localTruth||{});
  room.scores=settleAuditedHand(room,room.scores,state.localTruth||{},winner,points);room.envidoAudit=null;
  room.scores=capScores(room,settleSingleFlor(room,room.scores));
  const reason=auditResult.liars.length?`${room.players[auditResult.liars[0]].name} declaró mal${auditResult.liars.length>1?' primero':''}. ${room.players[auditResult.winner].name} gana el envido y la mano.`:ending==='falta'?'Falta envido: se verifican los tantos y se asignan los puntos en juego.':ending==='fold'?'Cuando te vas al mazo, el rival gana los puntos que estaban en juego hasta ese momento.':ending==='declined'?`${room.players[otherPlayer(winner)].name} dijo NO QUIERO. ${room.players[winner].name} gana ${points} ${points===1?'punto':'puntos'} por los puntos que estaban en juego hasta ese momento y se vuelve a repartir.`:`${room.players[winner].name} gana la mano (${points} puntos).`;
  room.lastHandScore=buildHandSummary(before,room.scores,reason,state.localTruth||{});room.handScoreEntries=[];
  room.handScoreHistory=handScoreHistory(room,room.lastHandScore);
  queueLearningPoints(before,room.scores,room.lastHandScore.entries);
  if(state.learning?.stage===0){state.learning.completedHands=(state.learning.completedHands||0)+1;if(state.learning.completedHands>=3&&!state.learning.hasCalledTruco){state.learning.trucoReminderPending=true;state.learning.trucoReminderAfterHand=room.handNumber;}}
  if(groups.length){localShowEvidence(groups);renderGame();return;}
  localDealAfterHand();
}
function localShowEvidence(groups){
  const room=state.room,delay=state.learning?3000:5000;
  room.status='revealing';room.pendingBet=null;room.trickCards=[];room.turn=null;room.endReveal={id:crypto.randomUUID(),endsAt:gameTime()+delay,groups};
  scheduleLocalTransition(room,()=>{if(!state.localGame||state.room!==room||room.status!=='revealing')return;localDealAfterHand();},delay);
}
function localDealAfterHand(){
  if(state.learning&&(state.learning.scoreMessages?.length||state.learning.activeScoreMessage)){
    state.learning.afterScoreMessage=localDealAfterHand;renderGame();return;
  }
  if(finishLearningHand())return;
  const room=state.room;
  if(Math.max(...Object.values(room.scores))>=targetPoints(room)){room.status='complete';room.pendingBet=null;room.endReveal={done:true};renderGame();return;}
  const deck=learningDeck(room),mano=otherPlayer(room.mano);
  state.localHands={player1:deck.slice(0,3),player2:deck.slice(3,6)};
  state.localOriginalHands=structuredClone(state.localHands);
  state.localTruth={player1:handEnvido(state.localHands.player1,deck[6]),player2:handEnvido(state.localHands.player2,deck[6])};
  Object.assign(room,{status:'started',resolutionEndsAt:null,resolvingTrick:false,endReveal:null,mano,dealer:otherPlayer(mano),turn:mano,handNumber:room.handNumber+1,tricks:[],trickCards:[],trickNo:1,muestra:deck[6],deckCount:33,playedCount:0,trucoLevel:1,pendingBet:null,lastTrucoCaller:null,flors:{},florSettled:false,envidoClosed:false,callNotice:null});
  state.hand=[...state.localHands[state.playerId]];
  localFeed(`${room.players[room.dealer].name} reparte. Empieza ${room.players[mano].name}.`);renderGame();
}
function canFoldHand(room,player){
  return !!room&&['player1','player2'].includes(player)&&room.status==='started'&&!room.resolvingTrick&&!room.pendingNextHand;
}
function foldHandChanges(room,loser){
  const winner=otherPlayer(loser),points=Number(room.trucoLevel)||1;
  const message=(room.players?.[loser]?.name||'El jugador')+' se fue al mazo. '+(room.players?.[winner]?.name||'El rival')+' gana la mano y suma '+points+' '+(points===1?'tanto.':'tantos.');
  const bet=room.pendingBet,sideChanges={};
  if(bet&&['envido','flor'].includes(bet.type)){
    const sidePoints=bet.revealMode?Number(bet.stake)||0:bet.type==='flor'?declinedFlorPoints(bet):Number(bet.accepted)||1;
    const scores={...room.scores};
    scores[winner]=(Number(scores[winner])||0)+sidePoints;
    sideChanges.scores=capScores(room,scores);
    sideChanges.envidoClosed=true;
    if(bet.type==='flor')sideChanges.florSettled=true;
  }
  const notice={kind:'fold',id:crypto.randomUUID(),from:loser,to:winner,text:(room.players?.[loser]?.name||'El rival')+' se fue al mazo.',spoken:'Me voy al mazo',time:Date.now(),handNumber:room.handNumber||1};
  return {...sideChanges,callNotice:notice,turn:null,turnClock:null,pendingBet:null,pendingNextHand:{id:'fold:'+crypto.randomUUID(),winner,foldPoints:points,message,endsAt:gameTime()+3000},feed:topFeed(room,message)};
}
function turnClockPlayer(room=state.room){
  if(room?.status==='timed-out')return room.turnTimeout?.loser||otherPlayer(room.turnTimeout?.winner);
  if(room?.pendingBet)return room.pendingBet.revealMode?room.pendingBet.revealTurn:room.pendingBet.responder;
  return room?.turn;
}
function turnClockKey(room=state.room){
  if(state.learning&&state.localGame)return null;
  if(room?.status==='timed-out'&&room.turnTimeout)return ['timeout',room.handNumber||1,room.turnTimeout.loser||otherPlayer(room.turnTimeout.winner),room.timeoutCounts?.[room.turnTimeout.loser||otherPlayer(room.turnTimeout.winner)]||1].join(':');
  if(!room||room.status!=='started'||room.resolvingTrick||room.pendingNextHand||room.endReveal&&!room.endReveal.done)return null;
  const player=turnClockPlayer(room);
  if(!['player1','player2'].includes(player))return null;
  const bet=room.pendingBet;
  if(bet)return ['bet',room.handNumber||1,room.trickNo||1,room.playedCount||0,bet.type,bet.called||'',bet.stake||0,bet.caller,player,bet.revealMode?'reveal':'answer',Object.keys(bet.reveals||{}).length].join(':');
  return [room.handNumber||1,room.trickNo||1,room.playedCount||0,player].join(':');
}
function turnClockRemaining(clock,now=gameTime()){
  const elapsed=Math.max(0,now-Number(clock.startedAt));
  return {extra:elapsed>=30000,seconds:Math.max(0,Math.ceil(((elapsed<30000?30000:45000)-elapsed)/1000)),expired:elapsed>=45000};
}
function turnTimeoutChanges(room){
  const loser=turnClockPlayer(room),winner=otherPlayer(loser);
  const timeoutCounts={...(room.timeoutCounts||{})};
  timeoutCounts[loser]=(Number(timeoutCounts[loser])||0)+1;
  const name=room.players?.[loser]?.name||'El jugador';
  if(timeoutCounts[loser]<3){
    return {timeoutCounts,status:'timed-out',turn:null,turnClock:null,pendingBet:null,turnTimeout:{winner,loser,message:name+' agotó su tiempo y pierde la mano ('+timeoutCounts[loser]+' de 3 faltas por inactividad).'}};
  }
  const message=name+' agotó los 45 segundos por tercera vez y pierde la partida. '+(room.players?.[winner]?.name||'El rival')+' gana por inactividad.';
  return {timeoutCounts,status:'complete',turn:null,turnClock:null,turnTimeout:null,
    scores:{...room.scores,[winner]:targetPoints(room)},
    matchResult:{winner,loser,reason:'inactivity',message},
    pendingBet:null,pendingNextHand:null,resolvingTrick:false,resolutionId:null,resolutionEndsAt:null,
    resolvedWinner:null,resolvedTrickWinner:null,handComplete:false,trickCards:[],envidoAudit:null,
    endReveal:{done:true},feed:topFeed(room,message)};
}
function save(){session.hands=state.localHands;session.originals=state.localOriginalHands;session.truth=state.localTruth;return session;}
function clock(){const key=turnClockKey();if(!key){state.room.turnClock=null;return;}if(state.room.turnClock?.key!==key)state.room.turnClock={key,startedAt:now};}
function dealOpening(){const room=state.room,draw=room.openingDraw;
 if(draw.cards.player1.rank===draw.cards.player2.rank){session.drawPool=deckFactory();room.openingDraw={cards:{},endsAt:now+30000};localFeed('Empate en el saque. Vuelvan a tocar el mazo.');return;}
 const dealer=draw.cards.player1.rank>draw.cards.player2.rank?'player1':'player2';
 room.mano=dealer;room.status='started';room.handNumber=0;room.scores={player1:0,player2:0};localDealAfterHand();
}
function advance(){const room=state.room;
 if(room.status==='drawing'){
  const draw=room.openingDraw;draw.cards??={};
  if(draw.cards.player1&&draw.cards.player2){if(now>=draw.resolveAt)dealOpening();}
  else if(now>=draw.endsAt){room.status='closed';room.closeReason='draw-timeout';}
 }
 if(room.resolvingTrick&&now>=room.resolutionEndsAt){
  const winner=settleHand(room.tricks,room);room.resolvingTrick=false;room.resolutionEndsAt=null;room.handComplete=false;room.trickCards=[];
  if(winner)localFinishHand(winner,room.trucoLevel||1);else{room.turn=room.resolvedTrickWinner||room.mano;room.trickNo++;}
 }
 if(room.pendingNextHand&&now>=room.pendingNextHand.endsAt){const pending=room.pendingNextHand;room.pendingNextHand=null;localFinishHand(pending.winner,pending.foldPoints,pending.id.startsWith('fold:')?'fold':'declined');}
 if(room.status==='revealing'&&now>=room.endReveal.endsAt)localDealAfterHand();
 if(room.status==='complete'&&!room.endReveal){const groups=buildEndEvidence(room,state.localOriginalHands);if(groups.length)localShowEvidence(groups);else room.endReveal={done:true};}
 if(room.status==='started'&&room.turnClock&&turnClockRemaining(room.turnClock,now).expired){const changes=turnTimeoutChanges(room);Object.assign(room,changes);if(room.status==='timed-out'){localFeed(room.turnTimeout.message);localFinishHand(room.turnTimeout.winner,room.trucoLevel||1);}}
 clock();return save();
}
function action(player,command){
 state.playerId=player;state.hand=localHand(player);advance();const room=state.room;
 if(!['player1','player2'].includes(player))throw new Error('Invalid player.');
 if(command.kind==='draw'){
  if(room.status!=='drawing'||room.openingDraw.cards[player])throw new Error('El sorteo ya cambió.');
  room.openingDraw.cards[player]=session.drawPool.shift();if(room.openingDraw.cards.player1&&room.openingDraw.cards.player2)room.openingDraw.resolveAt=now+2000;
 }else{
  if(room.status!=='started'||room.resolvingTrick||room.pendingNextHand)throw new Error('Esperá a que termine la pausa.');
  if(command.kind==='play'){if(room.turn!==player||room.pendingBet)throw new Error('No te corresponde jugar una carta.');const card=localHand(player).find(c=>c.id===command.cardId);if(!card)throw new Error('Esa carta no está en tu mano.');localPlay(card);}
  else if(command.kind==='call'){
   if(!['truco','retruco','vale4','envido','real','falta','flor','yes','no','raise','raise-envido','raise-real','raise-falta','raise-conflor','raise-faltaflor'].includes(command.value))throw new Error('Canto inválido.');
   if(['yes','no','raise'].includes(command.value)||command.value.startsWith('raise-')){if(!room.pendingBet||room.pendingBet.responder!==player||room.pendingBet.revealMode)throw new Error('No te corresponde responder.');}
   if(command.value.startsWith('raise-')&&room.pendingBet?.type==='envido'&&!['raise-envido','raise-real','raise-falta'].includes(command.value))throw new Error('Respuesta inválida para envido.');
   if(command.value.startsWith('raise-')&&room.pendingBet?.type==='flor'&&!['raise-conflor','raise-faltaflor'].includes(command.value))throw new Error('Respuesta inválida para flor.');
   if(command.value.startsWith('raise-')&&room.pendingBet?.type==='truco')throw new Error('Respuesta inválida para truco.');
   if(command.value==='raise'&&room.pendingBet.stake>=4)throw new Error('No se puede subir vale cuatro.');
   localAction(command.value);
  }else if(command.kind==='declare')revealEnvido(command.good===true,command.value);
  else if(command.kind==='fold'){if(!canFoldHand(room,player))throw new Error('No podés irte al mazo ahora.');Object.assign(room,foldHandChanges(room,player));}
  else throw new Error('Acción inválida.');
 }
 advance();return save();
}
return {action,advance};
}
function serverDeck(){const cards=[];for(const [suit,name] of [['♦','oro'],['♥','copa'],['♠','espada'],['♣','basto']])for(const rank of [1,2,3,4,5,6,7,10,11,12])cards.push({id:name+'-'+rank,rank,suit,red:['♦','♥'].includes(suit),label:String(rank)});for(let i=cards.length-1;i>0;i--){const j=crypto.randomInt(i+1);[cards[i],cards[j]]=[cards[j],cards[i]];}return cards;}
function newSession(code,players,targetPoints,creditMatch,now=Date.now()){
 if(![10,20,30,40,50,60].includes(targetPoints))throw new Error('Puntaje inválido.');
 return {code,hands:{},originals:{},truth:{},drawPool:serverDeck(),room:{managedCredits:true,creditMatch,deviceMode:'two',status:'drawing',createdAt:now,matchNumber:creditMatch.matchNumber||1,targetPoints,table:players.player1,players,scores:{player1:0,player2:0},handNumber:1,trickNo:1,playedCount:0,tricks:[],trickCards:[],feed:[],trucoLevel:1,flors:{},timeoutCounts:{},openingDraw:{cards:{},endsAt:now+30000}}};
}
module.exports={createReferee,newSession};
