'use strict';
// Generated by scripts/build-credit-referee.cjs. Browser state is never trusted.
const crypto=require('node:crypto');
function createReferee(session,{now=Date.now(),deckFactory=serverDeck}={}){
const state={room:session.room,roomCode:session.code,localGame:true,playerId:'player1',localHands:session.hands||{},localOriginalHands:session.originals||{},localTruth:session.truth||{},hand:[]};
const VALID_TARGET_POINTS=[10,20,30,40,50,60];
const gameTime=()=>now;
const noop=()=>{};
const renderGame=noop,queueLearningPoints=noop,queueLearningAction=noop,queueLearningTrucoCall=noop,queueLearningRoundResult=noop,animatePlayedHandCard=noop,renderTurnTimer=noop,renderRoundPauseTimer=noop;
const liveActionsBlocked=()=>false,finishLearningHand=()=>false;
const learningDeck=()=>deckFactory();
const verifiedHandTruth=()=>state.localTruth;
const toast=text=>{throw new Error(text);};
const shakeTurnBadge=()=>{throw new Error('No es tu turno.');};
const pauseMessage=()=>state.room.resolvingTrick||state.room.pendingNextHand||state.room.status==='revealing';
const scheduleLocalTransition=noop,scheduleLocalNextHand=noop;
const $=()=>({dataset:{value:'0'}});
